import './globals.css'
import type {Metadata} from 'next'
import serverContext from 'server-only-context';

import {EncryptionCharacterRange, Noscrape} from "@noscrape/noscrape";
import {ReactNode} from "react";
import NoscrapeFont from "@/components/NoscrapeFont";


export const [useNoscrape, setNoscrape] = serverContext(new Noscrape('public/example.ttf', {
    characterRange: EncryptionCharacterRange.HIRAGANA
}))

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <head>
            <title>noscrape - demo</title>
            <NoscrapeFont />
            <style>
            </style>
        </head>
        <body className={"p-3"}>
            {children}
        </body>
        </html>

    )
}
