import './globals.css'
import type {Metadata} from 'next'
import {ReactNode} from "react";
import NoscrapeFont from "@/components/NoscrapeFont";


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <head>
            <title>noscrape - demo</title>
            <NoscrapeFont />
            <style>
            </style>
        </head>
        <body className={"p-3"}>
            {children}
        </body>
        </html>

    )
}
