import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import obfuscate from '@noscrape/noscrape'

export async function getStaticProps() {
  const data = {
    headline: "Welcome to noscrape :)",
    textline1: "can you programmatically read this content?",
    linksHead: "sources:",
    example1: "nextjs-example",
    example2: "@noscript/noscript",

  }

  const { value, font } = await obfuscate(data, __dirname+'/../../../public/fonts/example/example.ttf')

  return { props: {
      value,
      font: font.toString('base64')
    } 
  }
}

const Home: NextPage = ({ value, font }: any) => {

  const fontStyle = `
      @font-face {        
        font-family: 'noscrape-obfuscated';        
        src: url('data:font/truetype;charset=utf-8;base64,${font}');    
      }
  `

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
                { fontStyle }
        </style>
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          { value.headline }
        </h1>

        <p className={styles.description}>
          { value.textline1 }
        </p>

        <p className={styles.links}>
          <h3>{ value.linksHead }</h3>
          <br />
          <a href="https://github.com/schoenbergerb/noscrape-nexample" target='_blank'>{ value.example1 }</a><br /><br />
          <a href="https://github.com/schoenbergerb/noscrape" target='_blank'>{ value.example2 }</a>
        </p>

      </main>
    </div>
  )
}

export default Home
